### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by RaviUmraliya** [pay-theory/pay-theory-android#2]
When load Payment screen

Every time get Error
 paymentError{"reason":"Attempt to invoke virtual method \u0027java.lang.String com.paytheory.android.sdk.api.ChallengeOptions.getChallenge()\u0027 on a null object reference"}

and after click on Submit payment button

```
FATAL EXCEPTION: main
    Process: com.xxxx, PID: 24994
    java.lang.NullPointerException
        at com.paytheory.android.sdk.Transaction.transact(Transaction.kt:148)
        at com.paytheory.android.sdk.fragments.PayTheoryFragment.makePayment(PayTheoryFragment.kt:271)
        at com.paytheory.android.sdk.fragments.PayTheoryFragment.access$makePayment(PayTheoryFragment.kt:38)
        at com.paytheory.android.sdk.fragments.PayTheoryFragment$configure$1$1.onClick(PayTheoryFragment.kt:215)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by aron23** [comment]
The latest release should resolve this issue.
